services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init_traindb.sql:/docker-entrypoint-initdb.d/init_traindb.sql:ro

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  mc-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p local/${MINIO_BUCKET} || true &&
      tail -f /dev/null
      "

  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.5.0
    environment:
      GIT_SYNC_REPO: ${GIT_REPO}
      GIT_SYNC_BRANCH: ${GIT_BRANCH}
      GIT_SYNC_ROOT: /git
      GIT_SYNC_DEST: repo
      GIT_SYNC_PERIOD: ${GIT_SYNC_PERIOD}
      GIT_SYNC_ONE_TIME: "false"
    volumes:
      - gitvolume:/git

  spark_client:
    build:
      context: .
      dockerfile: Dockerfile.spark_client
    depends_on:
      - git-sync
      - postgres
      - minio
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
    volumes:
      - gitvolume:/git
    ports:
      - "2222:22"

  airflow:
    image: apache/airflow:3.1.5
    depends_on:
      - postgres
      - git-sync
      - spark_client
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgres:5432/postgres
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_SPARK_SSH: ssh://${SPARK_SSH_USER}:${SPARK_SSH_PASSWORD}@spark_client:22
    volumes:
      - gitvolume:/git
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install apache-airflow-providers-ssh psycopg2-binary &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname a --lastname a --role Admin --email a@a.com || true &&
      ln -sf /git/repo/dags /opt/airflow/dags &&
      airflow standalone
      "

volumes:
  pgdata:
  miniodata:
  gitvolume:
  airflow_logs:

